### ISSUE TITLE
Possible to analyze sharedassets?

### ISSUE THREAD

**Issue by MrTinto** [Unity-Technologies/UnityDataTools#1]
Hi,

Is it possible to use this tool to analyze/dump the data for a sharedassets file (e.g. sharedassets1.asset), or does it only work with asset bundles? I've been able to successfully analyze/dump assetbundles, but not the sharedassets, so I just want to know if that's intended to be supported, so I know whether it's worth me digging into it further or not...

Thanks

**Comment by francis-page** [comment]
Hi, sorry for the delay. As of now, it's not possible to analyze the content of the player data (the game's data files that are not AssetBundles). This is because the tool uses the TypeTree which is only included in AssetBundles. The purpose of the TypeTree is to be able to load a data file that was built with a different version of Unity. As the player data is always built at the same time as the game itself, there's no need for the TypeTree and it is not included.
We may eventually add a feature to enable the TypeTree in the player data as it can be useful for debugging purposes. I can't make any promise about this though.

**Comment by francis-page** [comment]
Starting in Unity 2021.2, you can force TypeTree generation for Player Data. To do so, you must enable the Diagnostic Switch in the Editor Preferences. UnityDataTool will then be able to analyze these files.
